car: 
  length: 1

global_path: global_path

trajectory:
  lookahead: 30
  total_time: 5
  local_path: local_path
  reference_velocity: 1
  
  
tracking:
  odom: /vesc/odom
  control: /vesc/low_level/ackermann_cmd_mux/output_control
  kp: 8.0
  kd: 2.0
  goal_threshold: 0.5
  
